### ISSUE TITLE
How to use HTTPS to access Domoticz

### ISSUE THREAD

**Issue by cuihaijun** [linuxserver/docker-domoticz#16]
This is a very stable docker, and when I use the following command, it works great:

sudo docker run-d--name=domoticz--net=bridge-v/volume2/docker/domoticz:/config-e tz=asia/shanghai-p 6144:6144-p 8585:8080 Linuxserver/domoticz:latest

But I want to use HTTPS to access Domoticz when I use this Docker configuration:

sudo docker run-d--name=domoticz--net=bridge-v/volume2/docker/domoticz:/config-v/volume2/docker/domoticz/keys:/ Keys-e tz=asia/shanghai-p 4443:1443-p 6144:6144-p 8585:8080 linuxserver/domoticz:latest Cert.pem--sslkey/keys/keyfile.pem

No running program, can help me how to configure command, thank you!

**Comment by cuihaijun** [comment]
Connecting with the non SSL port works ok, but connecting with teh SSL port doesn't work

**Comment by aptalca** [comment]
That last bit `Cert.pem--sslkey/keys/keyfile.pem` is not a valid command to run in docker, that's probably why it's not starting.

Just copy your cert file to the following location: `/config/keys/server_cert.pem` with that same name and use the following line to start:
`sudo docker run -d --name=domoticz --net=bridge -v/volume2/docker/domoticz:/config -e TZ=Asia/Shanghai -p 4443:1443 -p 6144:6144 -p 8585:8080 linuxserver/domoticz:latest`
Then you should be able to access it at port `4443`

**Comment by cuihaijun** [comment]
Thank you very much, install successfully according to your steps
