### ISSUE TITLE
custom icons doesn't work

### ISSUE THREAD

**Issue by dyter** [linuxserver/docker-domoticz#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by tobbenb** [comment]
That was very informative. If you don't supply a way to recreate the issue, I'm going to close this.

**Comment by tobbenb** [comment]
Closing the issue as you don't supply any info.
