### ISSUE TITLE
system alive checker (ping) doesn't work

### ISSUE THREAD

**Issue by dyter** [linuxserver/docker-domoticz#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by tobbenb** [comment]
Doesn't look like you care to supply any info, so I'm closing your issues.

**Comment by FearNaBoinne** [comment]
Stable image (linuxserver/domoticz - Stable), System Alive Checker does not seem to work.

Added the "Hardware" and set up 4 hosts that I can normally ping from the docker container (exec bash), but one of them is currently offline.
Looking at the switches it generated under devices, all 4 of them remain "OFF" even though 3 are online and responding.

What else would you like to know?

**Comment by FearNaBoinne** [comment]
PS: The switches 'last update' show as the time they were created... No updates since!

**Comment by tobbenb** [comment]
So this is a device you can add in the hardware section?
if so, I'll see if I can reproduce the error. Going to be end next week as I'm on vacation.

**Comment by FearNaBoinne** [comment]
No worries... I just ran into this and checked the existing bugs before creating a new one, and found this issue...

Steps to reproduce:
1) Go to Hardware, add new hardware of type "System Alive Checker (Ping)"
2) Go in to settings of new device and add ping targets
3) View targets as new switches in the Devices page, add to active devices for easier monitoring
4) Notice they remain "OFF" and last update timestamp is creating timestamp

PS: Enjoy your vacation! Don't lurk on Github!  ;)

**Comment by tobbenb** [comment]
Thanks for the info. Makes it easier when people care to supply other info than not working 🙂
Only lurking when bored, so no worries.

**Comment by FearNaBoinne** [comment]
> Thanks for the info. Makes it easier when people care to supply other info than not working 🙂
I hear ya! I used to be a programmer in a previous live, so I know what a pain it is to get zero data on a bug or issue...
If you need me to check or test something, let me know!

> Only lurking when bored, so no worries.
LOLz

**Comment by tobbenb** [comment]
When we merge the rebase to alpine 3.10, this should be fixed. Added the iputils package that use the real ping and not just busybox's built in ping.

**Comment by CHBMB** [comment]
This should be fixed now, closing

**Comment by DAVIZINH0** [comment]
sorry for coment on this closed issue. but i have a question. this works? i configure 3 devices and not change never, allways off :-(

**Comment by tobbenb** [comment]
It should work now. Have you updated your container?

**Comment by DAVIZINH0** [comment]
yes, im in the container with domoticz 4.11203
maybe i need to delete de hardware and create it again? i will try

edit: not works. y delete de system alive checker hardware.
Then i create 3 devices with their ip.
apears a new virtual device for each 3 devices.
Never change the status of the devices :-(

any idea?
