### ISSUE TITLE
Custom icon upload does not work

### ISSUE THREAD

**Issue by Freekers** [linuxserver/docker-domoticz#32]
Running tag: stable-4.9700
Platform: Synology
Description: When trying to upload custom icons, *nothing* happens if you press the 'Upload' button.
In the Chrome console, the following error is displayed: 
```
TypeError: $http.post(...).success is not a function
    at b.$scope.uploadFileToUrl (CustomIconsController.js:14)
    at b.$scope.UploadIconSet (CustomIconsController.js:34)
    at fn (eval at compile (angular.min.js:242), <anonymous>:4:159)
    at e (angular.min.js:288)
    at b.$eval (angular.min.js:151)
    at b.$apply (angular.min.js:151)
    at HTMLButtonElement.<anonymous> (angular.min.js:288)
    at HTMLButtonElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLButtonElement.y.handle (jquery-3.3.1.min.js:2`)
```
The error is caused by line 14 in file domoticz\www\app\CustomIconsController.js 
In Angular 1.6, the $http service has changed: you can't use .success and .error anymore. Instead, use .then. (From $http docs)

The error can be fixed as follows. Replace this:
```
.success(function (data) {
	if (data.status != "OK") {
		HideNotify();
		ShowNotify($.t('Error uploading Iconset') + ": " + data.error, 5000, true);
	}
	$scope.RefreshIconList();
})
.error(function (data) {
	HideNotify();
	ShowNotify($.t('Error uploading Iconset'), 5000, true);
});
```

By this:
```
.then(function(response) {
	//Success
	var data = response.data;
	if (data.status != "OK") {
		HideNotify();
		ShowNotify($.t('Error uploading Iconset') + ": " + data.error, 5000, true);
	}
	$scope.RefreshIconList();
}, function(response) {
	//Error
	HideNotify();
	ShowNotify($.t('Error uploading Iconset'), 5000, true);
}); 
```

Kindly incorporate this fix into the image. Thank you!

Source: https://www.domoticz.com/forum/viewtopic.php?t=24201

**Comment by tobbenb** [comment]
I would prefer domoticz fixing this bug since it's a domoticz bug and not related to the container itself.

**Comment by Freekers** [comment]
I opened an issue at Domoticz and they've implemented the fix into their development branch. Not sure if and when it'll get merged to master and whether or not it'll be backported to 4.9700 stable.

https://github.com/domoticz/domoticz/issues/2925
