### ISSUE TITLE
Size of RAM data

### ISSUE THREAD

**Issue by michass** [linuxserver/docker-domoticz#35]
Hi,
In my container RAM useage is big, but processes don't eat too much.
How to clead this data, or maybe transfer outside container to harddisk memory?

![image](https://user-images.githubusercontent.com/43785139/51606794-2f4e2180-1f13-11e9-8b0f-606fb7ad36fb.png)

![image](https://user-images.githubusercontent.com/43785139/51606811-3d9c3d80-1f13-11e9-8655-27f481efb55c.png)

Container restart helps, but it's not a answer.

**Comment by tobbenb** [comment]
RAM is used from the host. If you don't want it to use too much RAM, you have to limit the containers RAM.
[https://docs.docker.com/config/containers/resource_constraints/](https://docs.docker.com/config/containers/resource_constraints/)

This isn't a container issue as far as I see it, so I'm going to close this.

**Comment by michass** [comment]
Yes, I can limit usage, but then after few days domoticz page don't load properly. Only text with few icons. When RAM is "unlimited" problem not exist.

**Comment by tobbenb** [comment]
This is most likely an issue with domoticz, so not much we can do about the memory use.
