### ISSUE TITLE
Python issue.

### ISSUE THREAD

**Issue by michass** [linuxserver/docker-domoticz#38]
Hi,
I try, to install python plugin for xiaomi vacuum cleaner.
I have issue with python
`Command "/usr/bin/python3.6 /usr/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jvkktjvt/overlay --no-warn-script-location --no-binary :none: --only-binar
y :none: -i https://pypi.org/simple -- setuptools>=18.5 wheel "cffi>=1.8,!=1.11.3; python_implementation != 'PyPy'"" failed with error code 1 in None `

I found some topics about libffi-dev libssl-dev, but apt-get don't work.
Best Regards

**Comment by CHBMB** [comment]
`apt-get` won't work as it's specific to Debian/Ubuntu based containers.  This is using Alpine, so different package management.  

What python package are you actually trying to install?

**Comment by homerr** [comment]
Closing due to no response.
