### ISSUE TITLE
can't connect to 8080

### ISSUE THREAD

**Issue by ward0** [linuxserver/docker-domoticz#40]
Hello,

I'm running OSMC install on a PI3 and installed docker and then your domoticz container, the problem i'm having at the moment is that i can't connect to http://192.168.1.2:8080

osmc@osmc:~$ docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:22:28 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:26 2019
  OS/Arch:          linux/arm
  Experimental:     false

osmc@osmc:~$ ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:d8ff:fe59:ba6a  prefixlen 64  scopeid 0x20<link>
        ether 02:42:d8:59:ba:6a  txqueuelen 0  (Ethernet)
        RX packets 11  bytes 416 (416.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 94  bytes 16929 (16.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=-28605<UP,BROADCAST,RUNNING,MULTICAST,DYNAMIC>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        ether b8:27:eb:95:00:8b  txqueuelen 1000  (Ethernet)
        RX packets 9892828  bytes 8414432427 (7.8 GiB)
        RX errors 0  dropped 7  overruns 0  frame 0
        TX packets 4893864  bytes 544156239 (518.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 24346  bytes 2170124 (2.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24346  bytes 2170124 (2.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth5fc608c: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e002:66ff:fe27:ef0  prefixlen 64  scopeid 0x20<link>
        ether e2:02:66:27:0e:f0  txqueuelen 0  (Ethernet)
        RX packets 11  bytes 570 (570.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 123  bytes 24112 (23.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

osmc@osmc:~$ docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                                                    NAMES
7a40a0ff1ba7        linuxserver/domoticz   "/init"             3 minutes ago       Up 2 minutes        0.0.0.0:1443->1443/tcp, 0.0.0.0:6144->6144/tcp, 0.0.0.0:8080->8080/tcp   domoticz

        "Config": {
            "Hostname": "7a40a0ff1ba7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "1443/tcp": {},
                "6144/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PUID=1000",
                "PGID=1000",
                "TZ=Europe/London",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                                                                                                             in",
                "PS1=$(whoami)@$(hostname):$(pwd)$ ",
                "HOME=/config",
                "TERM=xterm"
            ],
            "Cmd": null,
            "Image": "linuxserver/domoticz",
            "Volumes": {
                "/config": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- 98723b7d-ls1 Build-da                                                                                                                                                             te:- 2019-02-18T23:04:55+00:00",
                "maintainer": "saarg"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a418691a84c36c7d400997994c47daa009734767d19ef303aff59d                                                                                                                                                             55d95c0154",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1443"
                    }
                ],
                "6144/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "6144"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/a418691a84c3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "228999e2b0269064a9a421f6ad0fe827731e56b13170716966ad0                                                                                                                                                             d457677434c",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "81bedc00dabe2378da6ace4cf23ddd28b2e6f2e69963f5                                                                                                                                                             19f17238fa659dea3f",
                    "EndpointID": "228999e2b0269064a9a421f6ad0fe827731e56b131707                                                                                                                                                             16966ad0d457677434c",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

surfing to http://172.17.0.2:8080 doesn't work either.

Can you help me?

Regards,
Ward

**Comment by aptalca** [comment]
What does the docker log show?

`docker logs domoticz`

**Comment by tobbenb** [comment]
If you already had it setup a couple of days ago and then updated the container today, this is caused by us setting the wrong branch to fetch latest version from. So we ended up building the latest stable instead of the development branch.

**Comment by ward0** [comment]
@tobbenb I installed everything (Docker and Container) yesterday evening from fresh.

@aptalca I will check logging tonight, do you need any information en plus?

**Comment by ward0** [comment]
@tobbenb @aptalca
I think i found the solution to my problem (can't test atm since at work).
I'm running OSMC on a PI3 so i'm already using port 8080 for the OSMC webui...

I'm correct that my container parameters must be:

https://github.com/linuxserver/docker-domoticz
docker create \
  --name=domoticz \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 8084:8080 \
  -p 6144:6144 \
  -p 1443:1443 \
  -v datadir:/config \
  --restart unless-stopped \
  linuxserver/domoticz

So i still connect to port 8080 inside the container, but i have to surf to http://192.168.1.2:8084 from outside the container.

**Comment by tobbenb** [comment]
Yes, you need to use a port that is not in use. Inside the container it's always running as port 8080, but you map the port to, in your case, 8084 and that is the port you use to connect to domoticz.

**Comment by ward0** [comment]
changing to 8084 fixed my problem :) i'm happy thx
@tobbenb
