### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Freekers** [linuxserver/docker-domoticz#41]
Thanks for fixing back the pipeline as it was (i.e. master/latest --> development branch of Domoticz Repository). Previously. I was unable to start my Domoticz instance since the last update of 20th of January, because master/latest was pointing to the master branch of the Domoticz Repository, which is equal to stable, causing Domoticz to complain about a database version mismatch. And since you cannot downgrade Domoticz anymore since V 4.9700, I was stuck with an old beta version. Anyway, thanks for fixing.

I suggest you also update the readme to reflect this change:

latest | Current latest head from **development** at https://github.com/domoticz/domoticz.

Kind regards.

**Comment by tobbenb** [comment]
This is in the Readme now, so closing this issue.

**Comment by Freekers** [comment]
For me it still says 'Current latest head from master', while it should say 'Current latest head from development' if I'm not mistaken.

**Comment by tobbenb** [comment]
Master is development for domoticz last I checked.

**Comment by Freekers** [comment]
AFAIK it's not. Development is development :)

**Comment by tobbenb** [comment]
Yeah,  remember now. They changed it. Going to change it when we do any changes to domoticz. Takes too long to build on arm for just a Readme change.

Actually they made the development branch the default, so it is master in a way. If you follow the link in the Readme it goes to the correct branch.

**Comment by CHBMB** [comment]
This should be fixed now, closing
