### ISSUE TITLE
Problem with Xiaomi gateway

### ISSUE THREAD

**Issue by michass** [linuxserver/docker-domoticz#43]
Hi, I have problem with Xiaomi gateway.
I Try on jaddahl package for Synology and works. It's build bug, or maybe something else?

![image](https://user-images.githubusercontent.com/43785139/53938859-c7622d80-40b1-11e9-902a-75d7540e964b.png)
![image](https://user-images.githubusercontent.com/43785139/53938883-d517b300-40b1-11e9-9eea-b9f244cc53c4.png)
![image](https://user-images.githubusercontent.com/43785139/53938951-0db78c80-40b2-11e9-803d-b9cda208b0e6.png)

**Comment by tobbenb** [comment]
A little bit unclear what the issue is, but it's complaining about the IP being wrong?
Please set language to English if posting screenshots. 
Have you tested the same version on both docker and synology package?

**Comment by michass** [comment]
IP is cutted and gateway don't work. Maybe this is problem.
Docker is ...533, syno is 538, maybe this issue is fixed in next build.
This docker image is newest at this time.

**Comment by tobbenb** [comment]
It doesn't look like the IP is cut, it says that the IP starts with 192.168. How does it look like on the synology package?
Did you copy/paste the IP, or write it manually? 
Be sure to check that there are no empty spaces in front of the IP.

**Comment by michass** [comment]
Already checked.
In Jaddahl package all IP are shown. and works.
Container domoticz show part of IP and don't work.
I don't know, that problem is with this, maybe Logs show part, but have valid IP.
Maybe  getaway plugin is different between ..533 and 538 and after new container image release problem disapear.

**Comment by michass** [comment]
New build same problem ..545 container.
Have someone Xiaomi gateway on docker?

**Comment by tobbenb** [comment]
Did you map the port?

**Comment by michass** [comment]
Yes, 9898 t9 9898

**Comment by homerr** [comment]
Is the Xiaomi container on the same docker host?

**Comment by michass** [comment]
I have xiaomi server for vacuum cleaner. But when i turn it off still the same.

**Comment by tobbenb** [comment]
So the gateway is another container?
What happens if you run domoticz in host network mode?

**Comment by michass** [comment]
In host mode working 💃 but how to change port? to 8084? and 8443?

**Comment by tobbenb** [comment]
Then you have an issue with the port mapping and not the container, so going to close the issue.

You can't change the ports when running in host mode, so you need to figure out which ports the gateway uses and map them.

**Comment by michass** [comment]
But how to check this?

**Comment by tobbenb** [comment]
This place is for reporting issues with the containers and not a support forum. If you need support, join our discord server and ask there. Or on our discourse forum, but more chance to get help on discord.

**Comment by Ex4l** [comment]
I'm facing the same issue.

You do realize that using the same namespace as host's for a container is considered as a bad practice and a gate for security vulnerability? 

That's what you are doing by running network in host mode.

Do you have a true solution for using your image with a Xiaomi gateway ?

**Comment by tobbenb** [comment]
I'm not sure what you are talking about regarding same namespace as host?

Where did I say that one have to run it in host network mode?

**Comment by Ex4l** [comment]
> I'm not sure what you are talking about regarding same namespace as host?
> 
> Where did I say that one have to run it in host network mode?

Hello.

It was for @homerr who said it.

I'll investigate a bit more and i think i'll open a new issue, it's really weird what's happening here.

I'm being able to ping the Xiaomi gateway from my container but domoticz seems to be unable to reach it.
