### ISSUE TITLE
Custom icons not working

### ISSUE THREAD

**Issue by hlugt** [linuxserver/docker-domoticz#49]
Previous related issues addressed code. Currently still missing is write permission to write the icons to /var/lib/domoticz/www/images folder. That folder and content is owned by root, the custom icons are tried to be written by abc.
(Noticed this by binding volume to this location, and otherwise adding the icons as root to said location)
It is sufficient to make abc the owner of the mentioned folder (ie: "chown -R abc:abc /var/lib/domoticz/www/images")
It would be great if this was build in.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Docker on a debian arm64v8 

na

na

na

**Comment by tobbenb** [comment]
You didn't have to close the other issue and open a new 😉
I'll take a look at the what can be done with the custom icon folder.

**Comment by tobbenb** [comment]
Don't you need to edit the switch_icons.txt file also?

**Comment by hlugt** [comment]
Hm, did not get notification of your question... I think the switch_icons.txt is not necessary. In my case the icons became available and visible in the drop down box and visible in the custom icons view webpage without touching the switch_icons.txt file. If  I look inside that file the custom icons I have added are not in.

**Comment by hlugt** [comment]
Ok maybe some extra info if maybe in doubt on whether to do this or not: the custom image is uploaded as a binary blob to the sqlite database. That one resides in the /config volume so will survive docker image switches. The image blobs are then pushed out to the /var/lib/domoticz/www/images folder on initialization to be used (I guess). The switch_icons.txt does not need to be changed for all to work.
As a workaround (as I do not want to build a further perfectly fine docker image and branch versions) I now have downloaded all default content of the images folder and its subfolders, and placed them in a local volume that I mount on top of the /var/lib/domoticz/www/images folder. It will thus inherit my local permissions and the plugdev group will allow it to merge. 
Unfortunately this will then not reflect possible image changes etc that domoticz maybe brings in the future, so a permission change on the folder is most optimal.

**Comment by tobbenb** [comment]
So the only thing we need to do is to change owner for the /var/lib/domoticz folder and all is good? That shouldn't be any problem doing.

**Comment by DAVIZINH0** [comment]
hello, is this solved?
im migration my domoticz setup (more than 200 devices) to a docker architectura (in synology) and i cant upload custom icons :-(

**Comment by CHBMB** [comment]
There's a pending PR just waiting for a final edit from @tobbenb 

Domoticz is a BIG build, so we try and minimise the number of rebuilds.  So there's one pending.

**Comment by DAVIZINH0** [comment]
thanks a lot for your fast reply. i keep configuring, and wait for icons (its not critical)
thanks!

**Comment by tobbenb** [comment]
I'll probably manage to do it this week. On holiday and working on an old house, so not much time on the computer.

**Comment by CHBMB** [comment]
This should be fixed now, closing
