### ISSUE TITLE
Stable image old version, pull request

### ISSUE THREAD

**Issue by ajterpstra** [linuxserver/docker-domoticz#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Docker linux 
Image on docker is not de latest stable form domoticz 

Docker hub image V4.10659
Domoticz latest stable version 4.10717

fix, new image on docker hub

**Comment by tobbenb** [comment]
If you hoover the mouse over the version, you will see that the build hash is 649306c, which is the commit of version 4.10717. So this is an issue domoticz need to fix.
Here is the link to the domoticz release page: https://github.com/domoticz/domoticz/releases
So we are actually building version 4.10717, but the webui wrongly displays the previous version.

**Comment by ajterpstra** [comment]
hi 
I apologize, now I see it.
It appears to be their problem indeed.

**Comment by tobbenb** [comment]
Actually, we do build the wrong version, but the reason is that domoticz doesn't tag their releases correctly. They will not update it until next stable is released.
domoticz/domoticz#3197

**Comment by ajterpstra** [comment]
Hi tobbenb,
I had just noticed that Stable Release 4.10717 adapted to a later Git hub version.
That is 4 days ago and he will be fine now.
Would you still like to manually re-set so that the image on Hub docker is updated
https://github.com/domoticz/domoticz/releases

**Comment by ajterpstra** [comment]
Thnx
