### ISSUE TITLE
No more support of arm32v6-latest tag

### ISSUE THREAD

**Issue by prisme60** [linuxserver/docker-domoticz#52]
It seems that armv6 images are no more generated on docker gub.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Alpine 3.9.0 on Raspberry pi 1

cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 000f
Serial          : 0000000021596408

alpine:\~$ docker pull
alpine:\~$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
linuxserver/domoticz   arm32v6-latest      87014d868e07        8 weeks ago         147MB

Please continue to support armv6 for the first version of the raspberry pi.
Because domoticz is written in C++ language, it has a very low CPU and memory footprint, and it is working fluently with this hardware.

**Comment by tobbenb** [comment]
Sorry, but we decided to drop support for armv6 as there would be too many tags to keep track off. It's not coming back.
you can however install domoticz natively on alpine.

**Comment by prisme60** [comment]
Just for your information, there is no native support for armhf for domoticz on alpine (Many other archs are supported but not armhf). Thats' why I am using your Docker image.
I will try to generate my own Docker image.
Thanks you for your support.
