### ISSUE TITLE
Questions about adding librarys

### ISSUE THREAD

**Issue by DAVIZINH0** [linuxserver/docker-domoticz#56]
Hello,
In first place, thanks a lot for this project its great to have de posibility to use domoticz in docker and power off the raspberry :-P
I use domoticz in raspberry and now im migrating it to docker in a synology nas (using the app docker of synology)
Im user of domoticz the last two years and very happy with it, more than 200 devices, and some scripts in dzvents and sh with crontab.
The more devices i have are xiaomi devices and tasmota because are very simple to implement in domoticz.

My question is about of some librarys that i need to use in domoticz for my xiaomi devices:
first for use xiaomi vacuum cleaner plugin:
https://github.com/mrin/domoticz-mirobot-plugin

and the the miirobo library for a IR emiter and a wifi plugs:
https://python-miio.readthedocs.io/en/latest/discovery.html#installation

I install it from terminal and works.

The problem is that every time i update the containter it stop works and i must make again. Logicall, its docker! jejeje.
Its posible to add this librarys to the master branch?

Maybe this is not the place to talk about librarys, exist any forum or specific place to talk about docker and domoticz?

Thanks a lot, and sorry. my english is bad, its not my natural languaje.

Regards!
-David-

**Comment by tobbenb** [comment]
This is better to discuss in our forum discourse.linuxserver.io.
It's possible to use our custom unit scripts to install the libraries on container boot.
Going to close this one.

**Comment by DAVIZINH0** [comment]
ok, thanks for the info, i will read the forum and post in it!
thanks a lot!!!
