### ISSUE TITLE
styles

### ISSUE THREAD

**Issue by boscorelly** [linuxserver/docker-domoticz#67]
hi,

is there a way to have an outside folder to put themes in ?

**Comment by tobbenb** [comment]
I haven't really looked at it. Where is it supposed to go?

**Comment by boscorelly** [comment]
they go in www/styles/

**Comment by Systemedic** [comment]
Hi,

Any update about this?
I would like to use machinon as theme but can't seem to install it

**Comment by tobbenb** [comment]
Sorry, I completely forgot about this and haven't had much time to look at it.

It will have to wait until I manage to move domoticz over to using ubuntu and domoticz own binaries. At the moment our build nodes dies half of the time we build it as it's taking half a day...

In the meantime you can check the blog post about customizing our containers and manage to do it that way.
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by Systemedic** [comment]
Thanks for the update! I'm not that of an expert in docker so leave the customizing for someone else ;-). Perhaps in the future :-).

**Comment by codex666-cenotaph** [comment]
Hi @Systemedic 

Just got this to work on my synology with the docker image. 
1. Download the machinon theme as a zip file from the git.
2. map a folder to "/var/lib/domoticz/www/styles/machinon" and drop the contents of the theme download in there you can select it in the settings.

Cheers

**Comment by tobbenb** [comment]
Closing this as the above post have a good way of handling this.
