### ISSUE TITLE
xiaomi gateway problem

### ISSUE THREAD

**Issue by boscorelly** [linuxserver/docker-domoticz#68]
hi,

i have a problem contacting my gateway.

My docker configu is working fine on my actual rpi so i just want to test on docker before moving on it.

The issue is ;

XiaomiGateway: unable to write command - Invalid key

Documentation says it may be due to blocked igmp snooping. Can it be blocked on the container ?

**Comment by boscorelly** [comment]
i currently use this config :

  domoticz:
    image: linuxserver/domoticz:latest
    container_name: domoticz
    restart: always
    volumes:
      - /datastore/domoticz/:/config
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
#      - WEBROOT=domoticz
    ports:
      - "8085:8080"
      - "6144:6144"
      - "1443:1443"
      - "9898:9898"
    expose:
      - "8085"
    network_mode: host

but it seems network mode is not working.

i have a container with homeassistant which is able to contact the gateway...

**Comment by tobbenb** [comment]
I don't have any experience with xiaomi gateway, so hard to say what is wrong from the limited info I have.
Host network mode works fine, so why do you say it's not working? Or do you mean that the xiaomi gateway doesn't work even using host network mode?

Looking at the Domoticz documentation, it's using UDP Multicast which as far as I know, should work if you use Host network mode.

**Comment by boscorelly** [comment]
I have one domoticz on pi zero working.
i have set up a docker on another rpi3 with docker. I have backuped and restored my configuration.
No one of the sensors or sockets are responding on the dockerized domoticz, but works well on the old pi zero.

**Comment by boscorelly** [comment]
do you know how to enabl multicast ?

**Comment by tobbenb** [comment]
> do you know how to enabl multicast ?

Yes, you need to use host network mode. Might also work if you set an IP for the container.
So you have not got it working at all in a container, right? The version on the PI Zero is not a container version?

**Comment by boscorelly** [comment]
i already enable host mode on the container.
on the pi zero it is not a container version, it is a classical version

**Comment by sinopsysHK** [comment]
Hello,

I have it working on ubuntu 18-04-3 and docker 1.5.
To make it work I indeed had to switch it in "host" network mode without further changes:
```
docker run -d \
  --name=mydomoticz \
  --net=host \
  -p 8084:8080 \
  -p 6144:6144 \
  -p 1443:1443 \
  -v vol_domoticz:/config \
  -v vol_domoticz_templates:/var/lib/domoticz/www/templates \
  linuxserver/domoticz
```

When starting the container Docker raise a warning to recall that in host mode port bindings do not apply.

**Comment by boscorelly** [comment]
> domoticz:
>    image: linuxserver/domoticz:latest
>    container_name: domoticz
>    restart: always
>    volumes:
>      - /datastore/domoticz/:/config
>    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
    ports:
      - "8085:8080"
      - "6144:6144"
      - "1443:1443"
      - "9898:9898"
    expose:
      - "8085"
    network_mode: host

**Comment by boscorelly** [comment]
this is my docker-compose config. even in host mode it doesnt work

**Comment by boscorelly** [comment]
fixed now in last version, don't know what have been done, didn't touch during 2 months...
