### ISSUE TITLE
Request: Your pyton version miss requests library (Domoticz-deCONZ)

### ISSUE THREAD

**Issue by nesalkiN** [linuxserver/docker-domoticz#69]
The Domoticz-deCONZ plugin requires the requests library to work.
https://github.com/Smanar/Domoticz-deCONZ#requirement

Also, pip wan't an upgrade:
> WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

Domoticz log:
> 2019-12-20 15:47:58.233 Error: (Deconz) Your pyton version miss requests library
> 2019-12-20 15:52:48.283 Error: (Deconz) To install it, type : sudo -H pip3 install requests | sudo -H pip install requests

To fix this:
(pip3 install --upgrade pip) - not really required but pip3 will complain
pip3 install requests

It would be great if this could be added to the container.

Thanks!

(using https://blog.linuxserver.io/2019/09/14/customizing-our-containers/ to add it myself for now)

**Comment by tobbenb** [comment]
Closing this as the rebase to ubuntu will have python 3 requests included.
