### ISSUE TITLE
domoticz apk add mosquitto-clients

### ISSUE THREAD

**Issue by grzegorz189** [linuxserver/docker-domoticz#70]
Hello or can you add
 domoticz apk add mosquitto-clients
because after each update I have to update
docker exec domoticz apk update
docker exec domoticz apk add mosquitto-clients

Thanks

**Comment by tobbenb** [comment]
I will add it in the rebase to alpine 3.11 on the stable branch. Not sure if we still do the development build, but if we do, I'll add it there also.
In the meantime you can add it using our customizing scripts. Read about it on webpage.
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by tobbenb** [comment]
Closing this as the ubuntu rebase will fix it.
