### ISSUE TITLE
[Enhancement] Settable web server container port

### ISSUE THREAD

**Issue by sinopsysHK** [linuxserver/docker-domoticz#72]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

To use Xiaomi gateway, we need to enable IP multicast which is achievable only in "host" network mode. So having the possibility to set the internal target port number for the web server (and https) would be convenient.

This could be feasible via env variables that could be set at container creation.

Currently to change it the only option is to get into the container and change launch script where ports are "hardcoded" (relying on default port for http server and set for https server). This is obviously not a docker way.

## Current Behavior

In "host" mode port mapping does not apply and so if port 8080 is already in use Domoticz container cannot start crashing due to conflicting port.

## Steps to Reproduce

1. start an nginx server listening on port 8080
2. start domoticz container with "--net=host"
3.
4.

## Environment
**OS:**      ubuntu 18.04.3
**CPU architecture:** x86_64
**How docker service was installed:**      docker installed from ubuntu package (1.5-1build1)

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=mydomoticz \
  --net=host \
  -p 8084:8080 \
  -p 6144:6144 \
  -p 1443:1443 \
  -v vol_domoticz:/config \
  -v vol_domoticz_templates:/var/lib/domoticz/www/templates \
  --restart unless-stopped \
  linuxserver/domoticz
```
Ports mappings are discarded by docker as stated in a warning.

## Docker logs

```
WARNING: Published ports are discarded when using host network mode
```

**Comment by tobbenb** [comment]
This is a perfect use case for our container modification support.
Check out https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

Change the port in the domoticz run file in /etc/services.d/domoticz and set it to the port you want and save the file somewhere. Then make a script that replaces the run file with your own at boot.
