### ISSUE TITLE
Port problem. How to change 8080 to 8084 in docker? 8080 port conflict with Adguard

### ISSUE THREAD

**Issue by spider7611** [linuxserver/docker-domoticz#74]
Hi,

Have a synology nas and want to move my 1 year old domoticz into docker.
The old domoticz use 8084 port and https 8443
When I set up this: 

docker create --name=domoticz --net=host -v /volume1/docker/domoticz/:/config -e TZ=Europe/Budapest -p 1443:1443 -p 6144:6144 -p 8084:8084 -p8443:8443 linuxserver/domoticz

Not use this ports because this: --net=host and the domoticz page reach on ip:8080
But it isn't good for me, because I use Adguard in docker and that is use this port too and can't run together. How can I change this 8080 port to 8084 and 1443 to 8443 like the old domoticz use?

**Comment by tobbenb** [comment]
This is a configuration issue and not a bug. Please use our discord or discourse forum for support.

You only need to change the host side and you need to use bridge networking.
