### ISSUE TITLE
GPIOs on Rasp Pi 4 not recognised by Domoticz

### ISSUE THREAD

**Issue by alan-rpi** [linuxserver/docker-domoticz#75]
## Expected Behavior
I defined 2 GPIO pins using "echo 6 > /sys/class/gpio/export " etc
After defining the hardware in Domoticz as Rasp Pi using Generic sysfs GPIO I went to the Devices tab and expected the 2 GPIOs to be found by Domoticz 

## Current Behavior
The List of devices was empty 

NOTE: I subsequently installed the joshuacox/mkdomoticz:arm  container and it worked. The only amendment to the linuxserver compose file (other than changing the image name) was to add privileged: true as directed by the Git website 

## Steps to Reproduce
I fully documented it in this posting [https://domoticz.com/forum/viewtopic.php?f=47&t=31472](url)

## Environment
**OS:**  Raspian Buster  (note this was an image from http://www.raspberry-asterisk.org/downloads/
**CPU architecture:** Rasp Pi 4 arm64  but I believe the Raspian OS is x32
**How docker service was installed:**      
curl -sSL https://get.docker.com | sh

As  described in the posting above using this compose file 
version: "2"
services:
  domoticz:
    container_name: domoticz
    image: linuxserver/domoticz:arm32v7-latest
    restart: unless-stopped     # openHAB has always
    volumes:
      - /home/pi/bin/hms/docker_volumes/domoticz_data/domoticz_data:/config
      - /sys:/sys
    environment:
      - PUID=1001   # user pi
      - PGID=1001   # user pi
      - TZ=Europe/London
    #     - WEBROOT=domoticz # optional for subfolder reverse proxy
    ports:
      - 18080:8080   # web ui set to 18080 as openHAB uses 8080
      - 6144:6144   # comms
      - 1443:1443   # comms
    # devices: # to be defined if needed, e.g for zigbee usb dongle
    # - path to device:path to device

## Docker logs

Sorry lost. If critical I could restore the linuxserver and if you tell me the location of the log files

PS I believe Domoticz requires WiringPi to access the GPIO. Is this in the linuxserver ?
Despite extensive web searches I could not find anyone using linuxserver to access GPIOs. All examples were accessing via MQTT or USB

**Comment by tobbenb** [comment]
Might be that the permissions are wrong for the /sys folders?
The other container you have tested might run domoticz as root.

What is WiringPi? A plugin or standalone package?

One thing not related is that you don't need to specify a arm tag. Simply use linuxserver/domoticz and docker will pull the correct arch.

Docker logs you can get by simply typing "docker logs container_name"

**Comment by alan-rpi** [comment]
Hi. Thanks for responding. I've been busy but I'm planning to move all my Home folder to another partition and restructure over the next few days. When I do that I will retry your image noting your points. 

WiringPi is  a package http://wiringpi.com/  The author says:

> There is a version of wiringPi hosted on Github. Do not use this version of wiringPi. It only exists to facilitate building the Ruby and Python wrappers which have been written by Gadgetoid. You may also find other versions of wiringPi on github – these have all been forked and changed to support different hardware platforms.

**Comment by alan-rpi** [comment]
Just found this re Wiring GPIO [https://www.domoticz.com/wiki/GPIO](url)
> Domoticz currently supports two ways of accessing the pins:
1. The CLASSIC way is to install a driver, like WiringPi or PiGPIO.
2. A newer way is to use SYSFS GPIO. This is a standardised way of connecting to pins that is used on a lot of devices, and can be used without a driver. It is the prefered method. You don't have to install any additional software for SYSFS to work. 

It's a bit confusing as other that installing WiringPi for Option 1, both methods use the Export GPIO to make the pins available within Domoticz. Maybe the WiringPi allows for more low level functionality via scripting.

So, it seems WiringGPIO is not needed, at least to meet my current needs.

**Comment by alan-rpi** [comment]
Hi. I've now rebuilt by containers as follows but no luck getting the GPIOs recognised

1. Ran sudo ./sysfs_init.sh a bash file to export pins 5,6,7 & 13
` ls /sys/class/gpio
export  gpio5  gpio7      gpiochip100  unexport
gpio13  gpio6  gpiochip0  gpiochip504
`

2. I updated the compose file to reflect my new volume paths. As you recommended I also removed the reference to arm32v7

> version: "2"
services:
  domoticz:
    container_name: domoticzLS
    image: linuxserver/domoticz
    restart: unless-stopped     # always to start when docker starta
    volumes:
      - /home/pi/hms/docker/domoticzLS-data:/config
      - /sys:/sys
    environment:
      - PUID=1001   # user pi
      - PGID=1001   # user pi
      - TZ=Europe/London
    ports:
      - 18080:8080   # set to 18081 - JC domoticz uses 2xxx
      - 16144:6144   # comms
      - 11443:1443   # comms
    # devices: # to be defined if needed, e.g for zigbee usb dongle
    # - path to device:path to device

3. I then ran the compose as user pi and the image was downloaded. 
> docker-compose -f domoticzLS-compose-file.yml up -d
Pulling domoticz (linuxserver/domoticz:)...
latest: Pulling from linuxserver/domoticz
7e23450e9bad: Pull complete
0bad229f206f: Pull complete
acee184a3c59: Pull complete
e3104aff486c: Pull complete
f6f7e5bcb852: Pull complete
937bd99ae90a: Pull complete
Digest: sha256:f873fef7a7b525ecb0f6e589e6bc513d89c9f6ac18459e6cd573f3b6a1a2f1b5
Status: Downloaded newer image for linuxserver/domoticz:latest
Creating domoticzLS ... done
pi@raspi4hms:~/hms/docker $

4. Started the Domoticz container in Portainer

5. Accessed Domoticz via browser  http://192.168.1.42:18080/#/Dashboard

6. I went to the Hardware tab and definded
>Name		Raspberry Pi 4 HMS
Type		Generic sysfs GPIO
Data Timeout	Disabled
Auto config devices	Yes
sysfsdebounce	Default
Enabled		Yes

7. I then went to the Devices tab but there were no devices listed. With another domoticz image I've installed each of the gpios are listed as a device automatically.

8. Here is the log

> 2020-03-04 23:37:52.196  Active notification Subsystems: gcm, http (2/13),
2020-03-04 23:37:52.201  Status: WebServer(HTTP) started on address: 0.0.0.0 with port 8080,
2020-03-04 23:37:52.209  Status: WebServer(SSL) started on address: 0.0.0.0 with port 1443,
2020-03-04 23:37:52.211  Starting shared server on: 0.0.0.0:6144,
2020-03-04 23:37:52.212  Status: TCPServer: shared server started...,
2020-03-04 23:37:52.212  Status: RxQueue: queue worker started...,
2020-03-04 23:37:54.236  Status: Sysfs GPIO: Startup - polling:no interrupts:no debounce:50msec inputs:0 outputs:0,
2020-03-04 23:37:54.237  Status: NotificationSystem: thread started...,
2020-03-04 23:37:54.238  Status: EventSystem: reset all events...,
2020-03-04 23:37:54.239  Status: EventSystem: reset all device statuses...,
2020-03-04 23:37:54.290  Status: Python EventSystem: Initalizing event module.,
2020-03-04 23:37:54.291  Status: EventSystem: Started,
2020-03-04 23:37:54.291  Status: EventSystem: Queue thread started...,
2020-03-04 23:37:54.622  Status: PluginSystem: Entering work loop.,
2020-03-04 23:38:46.927  Status: Incoming connection from: 192.168.1.15,
2020-03-04 23:39:54.353  Status: Sysfs GPIO: Worker stopped,
2020-03-04 23:40:29.615  Status: Sysfs GPIO: Startup - polling:no interrupts:no debounce:50msec inputs:0 outputs:0,
2020-03-04 23:41:08.506  Status: Sysfs GPIO: Worker stopped,
2020-03-04 23:41:08.530  Status: Sysfs GPIO: Startup - polling:no interrupts:no debounce:50msec inputs:0 outputs:0,
2020-03-04 23:41:45.817  Status: Sysfs GPIO: Worker stopped,
2020-03-04 23:41:45.841  Status: Sysfs GPIO: Startup - polling:no interrupts:no debounce:50msec inputs:0 outputs:0,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
2020-03-04 23:42:59.242  Status: Closing application!...,
2020-03-04 23:42:59.242  Status: Stopping worker...,
2020-03-04 23:42:59.243  Status: RxQueue: queue worker stopped...,
2020-03-04 23:42:59.743  Status: WebServer(HTTP) stopped,
2020-03-04 23:43:00.244  Status: WebServer(SSL) stopped,
2020-03-04 23:43:00.246  Status: TCPServer: shared server stopped,
2020-03-04 23:43:00.246  Status: Stopping all hardware...,
2020-03-04 23:43:00.246  Status: Sysfs GPIO: Worker stopped,
2020-03-04 23:43:00.246  Status: Scheduler stopped...,
2020-03-04 23:43:00.247  Status: EventSystem: Stopped...,
2020-03-04 23:43:00.247  Status: EventSystem: Queue thread stopped...,
2020-03-04 23:43:00.257  Status: EventSystem - Python stopped...,
2020-03-04 23:43:00.257  Status: NotificationSystem: thread stopped...,
2020-03-04 23:43:00.258  Status: PluginSystem: Exiting work loop.,
2020-03-04 23:43:00.269  Status: PluginSystem: Stopped.,
2020-03-04 23:43:00.269  Status: Mainworker Stopped...,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
2020-03-04 23:44:36.131  Status: Domoticz V4.11774 (c)2012-2020 GizMoCuz,
2020-03-04 23:44:36.131  Status: Build Hash: a06400e05, Date: 2020-03-03 14:41:00,
2020-03-04 23:44:36.131  Status: Startup Path: /var/lib/domoticz/,
2020-03-04 23:44:36.186  Status: PluginSystem: Started, Python version '3.7.5'.,
2020-03-04 23:44:36.191  Active notification Subsystems: gcm, http (2/13),
2020-03-04 23:44:36.193  Status: WebServer(HTTP) started on address: 0.0.0.0 with port 8080,
2020-03-04 23:44:36.199  Status: WebServer(SSL) started on address: 0.0.0.0 with port 1443,
2020-03-04 23:44:36.202  Starting shared server on: 0.0.0.0:6144,
2020-03-04 23:44:36.202  Status: TCPServer: shared server started...,
2020-03-04 23:44:36.203  Status: RxQueue: queue worker started...,
2020-03-04 23:44:38.227  Status: Sysfs GPIO: Startup - polling:no interrupts:no debounce:50msec inputs:0 outputs:0,
2020-03-04 23:44:38.229  Status: NotificationSystem: thread started...,
2020-03-04 23:44:38.229  Status: EventSystem: reset all events...,
2020-03-04 23:44:38.230  Status: EventSystem: reset all device statuses...,
2020-03-04 23:44:38.294  Status: Python EventSystem: Initalizing event module.,
2020-03-04 23:44:38.294  Status: EventSystem: Started,
2020-03-04 23:44:38.295  Status: EventSystem: Queue thread started...,
2020-03-04 23:44:38.649  Status: PluginSystem: Entering work loop.,
2020-03-04 23:44:57.864  Status: Sysfs GPIO: Worker stopped,
2020-03-04 23:45:04.413  Status: Sysfs GPIO: Startup - polling:no interrupts:no debounce:50msec inputs:0 outputs:0,			

9. Here is a list of the GPIOs. Note that gpio readall needed the lastest Wiring Pi to work on a Pi 4 http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/  suggesting there is compatibility issues with the Pi 4  [I've tried to format the layout but the formatting  all got ignored]
> i@raspi4hms:/tmp $ sudo gpio readall
 +-----+-----+---------+------+---+---Pi 4B--+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode  | V   | Physical    | V  | Mode | Name   | wPi  | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |          |         |    3.3v  |            |       |  1   |   | 2  |       |           | 5v          |         |        |
 |   2     |   8    |   SDA.1 |   IN    | 1    |  3   |   | 4  |       |           | 5v          |         |        |
 |   3     |   9    |   SCL.1 |   IN     | 1    |  5   |   | 6  |       |           | 0v          |         |        |
 |   4     |   7    | GPIO. 7 |   IN   | 1     |  7   |   | 8  | 0    | OUT  | TxD        | 15    | 14    |
 |          |         |      0v   |           |        |  9   |   | 10 | 0   | OUT  | RxD        | 16   | 15     |
 |  17    |   0    | GPIO. 0 |   IN   | 1     | 11  |    | 12 | 0 | OUT   | GPIO. 1   | 1     | 18    |
 |  27    |   2    | GPIO. 2 |  OUT | 0     | 13 |     | 14 |    |           | 0v           |        |         |
 |  22    |   3    | GPIO. 3 |  OUT | 0    | 15 |     | 16 | 0 | IN      | GPIO. 4   | 4     | 23     |
 |          |         |    3.3v |             |       | 17 |     | 18 | 0 | IN      | GPIO. 5   | 5     | 24    |
 |  10    |  12   |    MOSI |  OUT | 0    | 19 |     | 20 |   |            | 0v          |        |          |
 |   9     |  13   |    MISO |  OUT | 0    | 21 |     | 22 | 0 | IN      | GPIO. 6  | 6     | 25     |
 |  11    |  14   |    SCLK |  OUT | 0     | 23 |     | 24 | 0 | IN      | CE0        | 10   | 8       |
 |         |          |      0v   |           |       | 25 |     | 26 | 0 | IN      | CE1        | 11    | 7       |
 |   0    |  30    |   SDA.0 |   IN   | 1     | 27 |     | 28 | 1 | IN       | SCL.0   | 31     | 1      |
 |   5    |  21    | GPIO.21 |   IN | 1     | 29 |      | 30 |   |            | 0v        |          |        |
 |   6    |  22    | GPIO.22 |   IN | 1     | 31 |     | 32 | 0 | IN       | GPIO.26 | 26   | 12   |
 |  13   |  23    | GPIO.23 |  OUT | 0  | 33 |      | 34 |   |             | 0v         |         |       |
 |  19   |  24     | GPIO.24 |   IN | 0    | 35 |     | 36 | 0 | IN        | GPIO.27 | 27  | 16  |
 |  26   |  25    | GPIO.25 |  OUT | 0 | 37 |       | 38 | 0 | IN        | GPIO.28 | 28  | 20  |
 |         |          |      0v     |          |     | 39 |      | 40 | 0 | IN       | GPIO.29 | 29   | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V |    Physical     | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 4B--+---+------+---------+-----+-----+


Maybe this can help identify the problem.

Many thanks
Alan

**Comment by tobbenb** [comment]
Without looking too close to the post, have you tried using the device tag instead of a volume mount for the sys parts? It makes more sense to me to use device.

**Comment by reydecopas** [comment]
Installed over odroidc2, gpios appears on menu but activation do not work. If I remove the user abc, and running domoticz as root it works.

**Comment by reydecopas** [comment]
> Installed over odroidc2, gpios appears on menu but activation do not work. If I remove the user abc, and running domoticz as root it works.

solved: chmod a+w /sys/class/gpio/gpio214/value from the host

so I can keep s6-setuidgid abc /var/lib/domoticz/domoticz in the docker

**Comment by alan-rpi** [comment]
> Without looking too close to the post, have you tried using the device tag instead of a volume mount for the sys parts? It makes more sense to me to use device.

Thanks for the suggestion.

I have just tried this. I removed volume  - /sys:/sys in my compose file and added:
```
devices:  
      - /dev/gpiomem:/dev/gpiomem
```
Just to be sure I ran the bash file that sets the gpio pins and confirmed with gpio exports they had been set.

I left the Hardware at Generic sysfs GPIO as the only other option that seemed relevant (Raspberry GPIO Port) the log file said "This hardware is deprecated. Please transfer to the new SysFS hardware type"

Reran the compose file but the Domoticz still does see the GPIO pins. 

I tried adding privileged: true to the compose file and rerunning but it makes no difference.

I checked that gpiomem exists in both the Rasp pi and the Domoticz container:
Raspberry Pi   >>>> crw-rw---- 1 root gpio 247, 0 Mar 14 22:28 /dev/gpiomem
Dom Container >>> crw-rw---- 1 root 997 247, 0 Mar 22 18:09 /dev/gpiomem

Note the different Group ownership. Could this be the problem?

**Comment by saidlm** [comment]
Hi,
I had the same issue. The problem is caused by lack of permitions to appropriate /sys sub-folders. In host OS (Rasbian) is owned by user rood and access is granted to group gpio.
Domoticz running in container is under abc user. All you need is to create group gpio and add abc use to is.

docker exec -it <COINTAINER> /bin/bash
    groupadd -g 997 gpio
    usermod -a -G gpio abc
docker commit <COINTAINER> <IMAGE>

After that add vollume:  /sys:/sys with rw access to docker-compose.yml and recreate container using command: docker-compose up -d.

Hopefully it will help.


BTW, the same issue I had with SPI interface.
