### ISSUE TITLE
Loop detection breaks some domoticz/out relaying

### ISSUE THREAD

**Issue by xaos11** [linuxserver/docker-domoticz#79]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Sometime since I last updated my Domoticz container with Unraid, I noticed that domoticz/out is not relaying all messages. Looking into this it seems this is a known issue and can be addressed by either an updated Beta or Stable version.

------------------------------

## Expected Behavior
All messages sent to domoticz/in should be forwarded to domoticz/out

## Current Behavior
Certain messages do not get forwarded to domoticz/out because of the built in loop detection

## Steps to Reproduce
https://www.domoticz.com/forum/viewtopic.php?f=6&t=31711&p=240110&hilit=mqtt#p240110

1. Add a device such as a THD. Sources such as DarkSky don't seem to be impacted. 
2. View output with mqtt.fx
3. Messages such as DarkSky will be repeated on domoticz/out, but my custom THD doesn't

## Environment
**OS: Unraid (latest)
**CPU architecture: x86_64
**How docker service was installed:**      
Installed from Unraid Apps (linuxserver\domoticz:latest)

## Command used to create docker container (run/create/compose/screenshot)
default Unraid template command

## Docker logs
Shouldn't need them?

Requesting to have either Beta version updated to 11921, Stable version possibly updated to 2020.1?

Thanks,
Ray

**Comment by tobbenb** [comment]
An update will come when we have rebased the container to ubuntu focal. I do not know when that will happen.

**Comment by tobbenb** [comment]
The ubuntu rebase will use 2020.2, so closing this.
