### ISSUE TITLE
Configure email notification with gmail

### ISSUE THREAD

**Issue by ldes89150** [linuxserver/docker-domoticz#83]
While setting up email notification with gmail, I encounter the following error message.

The `Active notification Subsystems: email (1/13)` changed from 2/13 to 1/13 after I install the openssl.

```
apk add openssl
```

## Environment
**OS:**      Debian 10
**CPU architecture:** x86_64  
**How docker service was installed:**      

```
docker run   --name=domoticz   -e PUID=1000   -e PGID=1000     -p 8083:8080      -v /database/domoticz:/config   --device /dev/ttyACM0:/dev/ttyUSB0   --restart unless-stopped   linuxserver/domoticz
```
## Docker logs
```
2020-07-02 20:03:11.084  Error: SMTP Mailer: Error sending Email to: <XXXXX@gmail.com> !
2020-07-02 20:03:11.084  Error: Failed to send Email notification!
2020-07-02 20:03:11.084  Notification sent (email) => Failed
2020-07-02 20:03:11.087  Active notification Subsystems: email (1/13)
```

**Comment by tobbenb** [comment]
Where do you set up Gmail notifications? I don't see anything about it in notification settings.

**Comment by ldes89150** [comment]
@tobbenb 

Sorry for causing the confusion. I set up the email settings with the Gmail SMTP server.

**Comment by tobbenb** [comment]
Is that a plugin?

**Comment by ldes89150** [comment]
No, i didn't use any plugins

**Comment by tobbenb** [comment]
Can you please tell me how you set it up in details?

**Comment by ldes89150** [comment]
sure!
It is under Setup >> Settings >> Email

I use the following configurations.
From:	mygmail@gmail.com
To:	<somemailaddress>
Server:	smtp.google.com
Port:	587
Username:	mygmail@gmail.com
Password:	mygmailpassword

After sending a test mail, it shows "notification sent", but the mail isn't sent actually.
Instead, I got the error message in the docker logs as described.

**Comment by tobbenb** [comment]
Don't know why I didn't see that....

Sending emails does work here not using a Gmail  account. Tested with Gmail and got the same error. You probably need to set some security setting in gmails setting to allow "insecure" applications.

So there is nothing wrong with the container.

**Comment by ldes89150** [comment]
@tobbenb The SMTP server you tested. Is it also using TLS? I suspect the problem comes from the TLS.

All my other applications (like grafana) can use Gmail's SMTP server without any issues, so I believe the problem comes from TLS.

Besides, I've installed Domoticz on Raspberry Pi before without docker, and it also works with Gmail.

**Comment by tobbenb** [comment]
I tested again with both SSL and TLS and both work. But you need to make an app password for domotics to use if you use two factor authentication.
https://support.google.com/mail/answer/185833?hl=en

But looking again at your email setup, you haven't filled out the to address.
