### ISSUE TITLE
[BUG] Fatal Python Error: pyinit_main: can't initialize time

### ISSUE THREAD

**Issue by zeddski** [linuxserver/docker-domoticz#88]
This issue is SOLVED by an issue on a different container, but I've placed it here for any googlers ending up here.
The solution can be found on https://docs.linuxserver.io/faq 

### ISSUE
Running crisp new instance on an RPi 4 (Debian), 2GB.

After starting the container, the logs show:
`domoticz    | Fatal Python error: pyinit_main: can't initialize time`
`domoticz    | Python runtime state: core initialized`
`domoticz    | PermissionError: [Errno 1] Operation not permitted`

### SOLUTION
https://docs.linuxserver.io/faq 

### REFERENCE
https://github.com/linuxserver/docker-papermerge/issues/4

### CONCLUSION
_This_ error has been fixed and now I get a different one (500 internal server error), but I'll analyze this one before opening a new issue.

**Comment by zeddski** [comment]
> 
> 
> Thanks for opening your first issue here! Be sure to follow the [issue template](https://github.com/linuxserver/docker-domoticz/blob/master/.github/ISSUE_TEMPLATE.md)!

That link goes nowhere...

**Comment by Roxedus** [comment]
> That link goes nowhere...

We know
