### ISSUE TITLE
please add the `git` executable

### ISSUE THREAD

**Issue by mprins** [linuxserver/docker-domoticz#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Having `git` available would make it possible to install plugins using the https://github.com/stas-demydiuk/domoticz-plugins-manager

## Current Behavior

`git` is not installed, so the recommended method of installing the plugin manager is not possible, also the plugin manager relies on `git` for installing and updating plugins so th eplugin manager would fail anyway.

## Alternatives Considered

using `curl` with `unzip` as a workaround for installing the plugin manager, however the plugin manager relies on `git` as you can see here: https://github.com/stas-demydiuk/domoticz-plugins-manager/blob/95ec06edd2eaafc344f6c22042b203da1f1ab630/manager.py#L74-L83

**Comment by tobbenb** [comment]
Git will not be included in the container.
You can read our blog post about customizing our containers https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
Or you could use the universal docker mod to add git. Check the readme for how to do it.

**Comment by mprins** [comment]
thanks, I'll give `https://github.com/linuxserver/docker-mods/tree/universal-git` a shot
