### ISSUE TITLE
Machanism to reduce logging

### ISSUE THREAD

**Issue by zubziro1** [linuxserver/docker-domoticz#91]
## Desired Behavior
I'm looking for some mechanism to reduce logging either by ENV parameter passed to docker or by altering ./scripts/domoticz.conf. I'm specially concerned to reduce logging of z-wave plugin/module as for right now it logs every value updates for each device.

Configurable ENV parameter LOG_LEVEL={normal,status,error}

## Current Behavior
Can't find any way to set loglevel. No ENV parameter to set log level and altering domoticz.conf seems to make no difference.

## Alternatives Considered
Probably the most generic way would be to add ENV ADDITIONAL_DAEMON_ARGS which would take string with any optional parameters to use for start of daemon.

**Comment by tobbenb** [comment]
Use the webroot env variable, but instead of entering a webroot, use the command line option for setting the log level.

**Comment by zubziro1** [comment]
> Use the webroot env variable, but instead of entering a webroot, use the command line option for setting the log level.

Thanks for suggestion!

Yeah sure as workaround it works ->
       - env:
            - name: WEBROOT
              value: '-loglevel 2'

Don't looks too pretty... but it works.

**Comment by tobbenb** [comment]
Closing as there is a work around
