### ISSUE TITLE
Allow to choose the path of the database

### ISSUE THREAD

**Issue by max3163** [linuxserver/docker-domoticz#92]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Allow to choose the path of the database with env parameter to change the command line dbase option.

## Current Behavior

The database is in the same config path

**Comment by tobbenb** [comment]
You haven't really made any arguments for why this is needed. If you can't come up with anything better, I'll close the issue.

**Comment by max3163** [comment]
I use domoticz on k8s and I would like to store the database on a different PV ( fast SSD volumes for database ) 
And the option already exist on domoticz, just allow user to use it.
Split conf and database is a good practice.

**Comment by tobbenb** [comment]
This is added in the latest version.
