### ISSUE TITLE
Bad permissions on /dev/ttyUSB0

### ISSUE THREAD

**Issue by Adelysnet** [linuxserver/docker-domoticz#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

On my Synology Nas, when the USB device is mounted, /dev/ttyUSB0  came with a 600 permission (root:root), so my ZWave Dongle is not working.

## Expected Behavior
USB should work without forcing root user.

## Current Behavior
abc user is not allowed to read/write /dev/ttyUSB0.

## Steps to Reproduce
--

## Environment
**OS: DSM 6.2
**CPU architecture: x86_64
**How docker service was installed: Official repo from Synology Docker GUI

## Command used to create docker container (run/create/compose/screenshot)
**

## Docker logs
**

**Comment by tobbenb** [comment]
Closing due to template not fully filled
