### ISSUE TITLE
Can you include speedtest-cli in the image?

### ISSUE THREAD

**Issue by pgolawsk** [linuxserver/docker-domoticz#99]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Domoticz plugin for measuring internet connection speed do need it to operate, The plugin is there , but the speedtest package not.
Once Speedtest plugin in Domoticz is enabled then it collects upload,download and ping.

## Current Behavior

Once Speedtest plugin in Domoticz is enabled then no measures are collected and there are errors in log, showing speedtest-cli is not installed.

## Alternatives Considered

I've used to install into the docker image after container is created, but it require redo every time I pull the latest image from linuxserver repository.

**Comment by drizuid** [comment]
i would suggest a docker-mod for now: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
